### ISSUE TITLE
Add example code to wiki

### ISSUE THREAD

**Issue by jalanb** [bitwrap/bitwrap-io#1]
https://bitwrap.github.io/ gives access to 3 demo projects: Terminal, TicTacToe and Counter.
May I suggest that the sources for them be linked from the main wiki page, or even from the README?

I could not find these sources in the repository, or this would be a pull request.

**Comment by stackdump** [comment]
Thanks for the feedback - will try to make examples more thorough

**Comment by stackdump** [comment]
Updated the Wiki to link to examples: https://github.com/bitwrap/bitwrap-io/wiki
