### ISSUE TITLE
simulation results in invalid state

### ISSUE THREAD

**Issue by stackdump** [bitwrap/bitwrap-io#4]
currently there is a redis lock around commits, but this doesn't seem to be sufficient 

when running several simultaneous requests we can cause the storage to end up in an invalid state ( i.e. stored a negative value which is not allowed )

run the simulator in bitwrap-ui
```
App.session.simulation(['gir', 'zim', 'gaz', 'dib', 'tak']).run()
```

observe the invalid state on server 

```
bitwrap@f60f2329e649:/repo/karmanom.com$ cat zim
[0,0,0,0,0,0,0,1,1,1,-1,1,1]bitwrap@f60f2329e649:/repo/karmanom.com$ 
```

**Comment by NDuma** [comment]
Negative State storage; it might be useful to have.

**Comment by stackdump** [comment]
@NDuma  the idea is to be able to easily validate valid transactions - you can't give a token you don't have - I may reconsider later if we find a better use case, but currently using tokens means sticking to natural numbers + 0

**Comment by stackdump** [comment]
FYI this is being caused by race conditions when 2 processes write to storage around the same time - I may solve this by caching all values in  redis  - and execute in a block using 'multi' and 'watch' 
http://stackoverflow.com/questions/15776955/redis-watch-multi-exec-by-one-client

Here's another example of a failure where 4 items are written while only 2 zim, gir should have been affected by this signal

````
From 5ef5b48e64825259f29f5a98892a286d5795403c Mon Sep 17 00:00:00 2001
From: zim <zim>
Date: Sat, 4 Jun 2016 06:18:12 +0000
Subject: [PATCH 01/21] 
 {"sender":"zim","target":"gir","action":"deposit_system","payload":{"message_id":"14"}}

---
 dib | 2 +-
 gir | 2 +-
 tak | 2 +-
 zim | 2 +-
 4 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/dib b/dib
index 4f95204..576f7b4 100644
--- a/dib
+++ b/dib
@@ -1 +1 @@
-[0,0,0,0,0,0,0,1,1,1,1,3,1]
\ No newline at end of file
+[0,0,0,0,0,0,0,1,1,1,1,2,1]
\ No newline at end of file
diff --git a/gir b/gir
index e35f8eb..a7898f9 100644
--- a/gir
+++ b/gir
@@ -1 +1 @@
-[0,0,0,0,0,0,0,1,1,1,1,1,2]
\ No newline at end of file
+[0,0,0,0,0,0,0,1,1,1,1,2,0]
\ No newline at end of file
diff --git a/tak b/tak
index 3877ce8..eed2d19 100644
--- a/tak
+++ b/tak
@@ -1 +1 @@
-[0,0,0,0,0,0,0,1,1,1,1,0,1]
\ No newline at end of file
+[0,0,0,0,0,0,0,1,1,1,1,1,1]
\ No newline at end of file
diff --git a/zim b/zim
index 5d726a6..4f95204 100644
--- a/zim
+++ b/zim
@@ -1 +1 @@
-[0,0,0,0,0,0,0,1,1,1,0,2,1]
\ No newline at end of file
+[0,0,0,0,0,0,0,1,1,1,1,3,1]
\ No newline at end of file
-- 
2.1.4

````

**Comment by stackdump** [comment]
this issue was resolved by adding a file system lock around each transformation event https://github.com/bitwrap/bitwrap-io/commit/20749b5399cdc5c536ca024fc0a5069d54082135

I'm going to add another ticket for caching state-vector values in redis as I believe that disk IO is the current bottleneck
